_target_: mldft.datagen.datasets.misc.MiscXYZ
name: MiscXYZ
filename: misc

raw_data_dir: ${oc.env:DFT_DATA}/${dataset.name}/raw/
kohn_sham_data_dir: ${oc.env:DFT_DATA}/${dataset.name}/kohn_sham/
label_dir: ${oc.env:DFT_DATA}/${dataset.name}/labels/
