_target_: mldft.datagen.datasets.qmugs.QMUGSLargeBins
name: QMUGS
filename: qmugs

raw_data_dir: ${oc.env:DFT_DATA}/${dataset.name}/raw
kohn_sham_data_dir: ${oc.env:DFT_DATA}/${dataset.name}/kohn_sham
label_dir: ${oc.env:DFT_DATA}/${dataset.name}/labels
use_original_ids: true
