_target_: mldft.datagen.datasets.qmugs.QMUGSBin
name: QMUGS
filename: qmugs

raw_data_dir: ${oc.env:DFT_DATA}/${dataset.name}/raw
kohn_sham_data_dir: ${oc.env:DFT_DATA}/${dataset.name}/kohn_sham
label_dir: ${oc.env:DFT_DATA}/${dataset.name}/labels
bin: 0
