# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# output directory, generated dynamically on each run
run:
  dir: ${base_dir}/${dir_counter:${base_dir},3}_${smart_override_dirname:${hydra.job.override_dirname},run_path}

sweep:
  dir: ${oc.env:MODELS}/${task_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  subdir: ${hydra.job.num}

job_logging:
  handlers:
    file:
      # Incorporates fix from https://github.com/facebookresearch/hydra/pull/2242
      filename: ${hydra.runtime.output_dir}/${task_name}.log

callbacks:
  git_logging:
    _target_: mldft.utils.log_utils.hydra_callbacks.GitInfo
