# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# output directory, generated dynamically on each run
run:
  # see below for details
  dir: ${paths.log_dir}/${task_name}/runs/${dir_counter:${paths.log_dir}/${task_name}/runs,3}_${name}_${smart_override_dirname:${hydra.job.override_dirname}}
sweep:
  dir: ${paths.log_dir}/${task_name}/multiruns/${hydra.sweeper.study_name}
  # configuration for the subdirectory of each run. also note the exclude keys of override_dirname specified below.

  # longer form, with full keys and subkeys
  # subdir: ${dir_counter:${.dir},3}_${slash_to_backslash:${hydra.job.override_dirname}}

  # compact form, using only the leafs of the config (key.subkey.subsubkey=value -> subsubkey=value)
  # subdir: ${dir_counter:${.dir},3}_${leafs_only_override_dirname:${hydra.job.override_dirname}}

  # even compacter, values-only form (key.subkey.subsubkey=value -> value)
  # subdir: ${dir_counter:${.dir},3}_${values_only_override_dirname:${hydra.job.override_dirname}}

  # smart trade-off between the two above, specifying the subkeys for numeric values only
  subdir: ${dir_counter:${.dir},3}_${smart_override_dirname:${hydra.job.override_dirname}}

job_logging:
  handlers:
    file:
      # Incorporates fix from https://github.com/facebookresearch/hydra/pull/2242
      filename: ${hydra.runtime.output_dir}/${task_name}.log

job:
  config:
    override_dirname:
      exclude_keys:
        - name # already included in run.dir
        - hparams_search # specifics already in override_dirname
        - trainer

callbacks:
  git_logging:
    _target_: mldft.utils.log_utils.hydra_callbacks.GitInfo
