# Runs `pre-commit` on all files.

name: Code Quality

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:

jobs:
  code-quality:
    if: github.event_name == 'pull_request' && github.event.pull_request.draft == false || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Run pre-commits
        uses: pre-commit/action@v3.0.1
