name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check space before micromamba
        run: |
          df -h
        shell: bash -el {0}

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1.9.0
        with:
          environment-file: environment_cpu.yaml
          init-shell: bash
          cache-environment: true

      - name: Check space after micromamba
        run: |
          df -h
          du -h -d 1 $(dirname $(dirname $(dirname $(which python))))
        shell: bash -el {0}

      - name: List dependencies
        run: |
          python -m pip list
        shell: bash -el {0}

      - name: Install package
        run: |
          pip install -e .
        shell: bash -el {0}

      - name: Build documentation
        run: make docs
        shell: bash -el {0}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
