_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 1 # prevents early stopping
max_epochs: 90

# how often to log the scalars with on_step=True
log_every_n_steps: 200

inference_mode: False # Set to false to make torch.enable_grad() work

accelerator: auto
devices: 1

# mixed precision for extra speed-up
precision: 32

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1

# perform a validation loop every N training steps
# val_check_interval: 1000
# validate on a few batches only
# limit_val_batches: 0.5

# set True to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False
